dev:
  dockerfile: config/docker/dev
  build: .
  volumes:
    - ./:${PWD}
  working_dir: ${PWD}
  ports:
    - "3000:3000"
    - "9000:9000"
  environment:
    DATABASE_URL: 'postgres://user:password@db:5432'
  links:
    - db

db:
  image: postgres:9.6.3
  environment:
    POSTGRES_DB: leket
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports:
    - "5433:5432"